services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: