version: "3.6"

services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ktor-mongo
    environment:
      MONGO_CLIENT: mongodb://root:password@mongo:27017
    ports:
      - 8080:8080